/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        bg: 'var(--bg)',
        'bg-soft': 'var(--bg-soft)',
        surface: 'var(--surface)',
        ink: 'var(--ink)',
        'ink-2': 'var(--ink-2)',
        'ink-3': 'var(--ink-3)',
        line: 'var(--line)',
        'line-2': 'var(--line-2)',
        accent: 'var(--accent)',
        'accent-2': 'var(--accent-2)',
        'accent-soft': 'var(--accent-soft)',
        panel: 'var(--panel)',
        'panel-2': 'var(--panel-2)',
        'panel-text': 'var(--panel-text)',
        'panel-muted': 'var(--panel-muted)',
        'panel-line': 'var(--panel-line)',
        error: '#ba1a1a',
      },
      backgroundImage: {
        grad: 'linear-gradient(120deg, var(--accent), var(--accent-2))',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '18px',
        '3xl': '30px',
        full: '9999px',
      },
      spacing: {
        'margin-desktop': '40px',
        xs: '4px',
        sm: '12px',
        lg: '48px',
        xl: '80px',
        md: '24px',
        base: '8px',
        'margin-mobile': '16px',
        gutter: '24px',
      },
      fontFamily: {
        display: ['"Space Grotesk"', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        'headline-sm': ['"Space Grotesk"', 'sans-serif'],
        'headline-lg': ['"Space Grotesk"', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'body-sm': ['Inter', 'sans-serif'],
        'label-sm': ['Inter', 'sans-serif'],
        'headline-md': ['"Space Grotesk"', 'sans-serif'],
        'headline-lg-mobile': ['"Space Grotesk"', 'sans-serif'],
        'label-md': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'headline-sm': ['20px', { lineHeight: '26px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-lg': ['clamp(38px, 5.6vw, 70px)', { lineHeight: '1.06', letterSpacing: '-0.02em', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-lg': ['clamp(16.5px, 1.5vw, 19px)', { lineHeight: '1.62', fontWeight: '400' }],
        'body-sm': ['14.5px', { lineHeight: '20px', fontWeight: '400' }],
        'label-sm': ['11px', { lineHeight: '14px', letterSpacing: '0.03em', fontWeight: '500' }],
        'headline-md': ['clamp(28px, 3.6vw, 46px)', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-lg-mobile': ['32px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '600' }],
        'label-md': ['13px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '500' }],
      },
    },
  },
  plugins: [],
}
