/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-secondary-fixed-variant': '#3c475a',
        'surface': '#f7f9fb',
        'on-background': '#191c1e',
        'surface-bright': '#f7f9fb',
        'surface-dim': '#d8dadc',
        'on-primary-container': '#e5e8ff',
        'tertiary-fixed': '#d3e4fe',
        'secondary-fixed-dim': '#bcc7de',
        'on-tertiary-container': '#deeaff',
        'background': '#f7f9fb',
        'on-surface': '#191c1e',
        'on-secondary-fixed': '#111c2d',
        'surface-container-highest': '#e0e3e5',
        'surface-tint': '#1f4fdf',
        'secondary-fixed': '#d8e3fb',
        'tertiary-container': '#5a6a81',
        'inverse-primary': '#b7c4ff',
        'primary': '#0040cf',
        'surface-container-low': '#f2f4f6',
        'outline': '#747686',
        'outline-variant': '#c4c5d8',
        'primary-fixed-dim': '#b7c4ff',
        'on-tertiary': '#ffffff',
        'on-primary-fixed': '#001452',
        'primary-fixed': '#dde1ff',
        'on-surface-variant': '#434655',
        'tertiary-fixed-dim': '#b7c8e1',
        'surface-container': '#eceef0',
        'primary-container': '#2f5bea',
        'on-primary': '#ffffff',
        'surface-variant': '#e0e3e5',
        'on-tertiary-fixed': '#0b1c30',
        'secondary-container': '#d5e0f8',
        'on-error': '#ffffff',
        'tertiary': '#425268',
        'on-tertiary-fixed-variant': '#38485d',
        'surface-container-high': '#e6e8ea',
        'inverse-surface': '#2d3133',
        'secondary': '#545f73',
        'error': '#ba1a1a',
        'error-container': '#ffdad6',
        'on-secondary-container': '#586377',
        'on-primary-fixed-variant': '#0038b7',
        'on-secondary': '#ffffff',
        'inverse-on-surface': '#eff1f3',
        'surface-container-lowest': '#ffffff',
        'on-error-container': '#93000a',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'margin-desktop': '40px',
        xs: '4px',
        sm: '12px',
        lg: '48px',
        xl: '80px',
        md: '24px',
        base: '8px',
        'margin-mobile': '16px',
        gutter: '24px',
      },
      fontFamily: {
        'headline-sm': ['Inter', 'sans-serif'],
        'headline-lg': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'body-sm': ['Inter', 'sans-serif'],
        'label-sm': ['Inter', 'sans-serif'],
        'headline-md': ['Inter', 'sans-serif'],
        'headline-lg-mobile': ['Inter', 'sans-serif'],
        'label-md': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'headline-lg': ['40px', { lineHeight: '48px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-sm': ['11px', { lineHeight: '14px', letterSpacing: '0.03em', fontWeight: '500' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-lg-mobile': ['32px', { lineHeight: '38px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'label-md': ['13px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '500' }],
      },
    },
  },
  plugins: [],
}
